# Site settings
title: Coder's Diary
header-img: img/home-bg.jpg
email: reachdevi1993@gmail.com
copyright_name: Your/Project/Corporate Name
description: "A blog for put my ideas, experiences and analysis into words and to digitize the lessons learnt."
baseurl: ""
url: "http://yourdomain.com"
twitter_username: SBootstrap
github_username:  mfsirsdevi
facebook_username:  StartBootstrap
email_username:  reachdevi1993@gmail.com

# Google Analytics
# To enable google analytics, uncomment below line with a valid Google Tracking ID
# google_tracking_id:

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
